In [1]:
# Day 3 - NumPy Basics

import numpy as np

# 1. Create Arrays
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("1D Array:", arr1)
print("2D Array:\n", arr2)

# 2. Array Information
print("\nShape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)

# 3. Indexing
print("\nFirst Element:", arr1[0])
print("Last Element:", arr1[-1])

# 4. Slicing
print("First Three Elements:", arr1[:3])
print("Last Two Elements:", arr1[-2:])

# 5. Mathematical Operations
print("\nAddition:", arr1 + 10)
print("Multiplication:", arr1 * 2)
print("Square:", arr1 ** 2)

# 6. Array Calculations
print("\nSum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Maximum:", np.max(arr1))
print("Minimum:", np.min(arr1))

# 7. Matrix Operations
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("\nMatrix Addition:\n", a + b)
print("Matrix Multiplication:\n", np.dot(a, b))

print("\nDay 3 NumPy Basics Completed Successfully!")

1D Array: [10 20 30 40 50]
2D Array:
 [[1 2 3]
 [4 5 6]]

Shape: (2, 3)
Dimensions: 2
Data Type: int64

First Element: 10
Last Element: 50
First Three Elements: [10 20 30]
Last Two Elements: [40 50]

Addition: [20 30 40 50 60]
Multiplication: [ 20  40  60  80 100]
Square: [ 100  400  900 1600 2500]

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Multiplication:
 [[19 22]
 [43 50]]

Day 3 NumPy Basics Completed Successfully!
